# FROM ubuntu
FROM jacksoncage/varnish

# File Author / Maintainer
MAINTAINER Cameron Drake

# RUN apt-get update
# RUN apt-get upgrade -y --show-upgraded
# RUN apt-get install -y curl
# RUN curl http://repo.varnish-cache.org/debian/GPG-key.txt | apt-key add -
# RUN echo "deb http://repo.varnish-cache.org/ubuntu/ precise varnish-3.0" | tee -a /etc/apt/sources.list
# RUN apt-get update
# RUN apt-get install -y varnish

# EXPOSE 80
